[JN-1119] More AT changes
broadinstitute/pearl pull request #1021
Opened 2024-07-25 14:30 UTC by connorlbark

#### DESCRIPTION (include screenshots, and mobile screenshots for participant UX)

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

2024-07-25 16:33 UTC, connorlbark commented on api-participant/src/main/java/bio/terra/pearl/api/participant/controller/SiteMediaController.java
> +        "https://sandbox.atcp.localhost:3001"
Temp change to allow testing: must delete before merge. I'm not really sure the best way to enable local testing, since I was (for some reason that I don't honestly fully understand) getting a CORS error locally without this. I think we should figure out - in a separate PR - how we want to handle this. Since this works just fine without a `@CrossOrigin` annotation, Matt suggested a `get` and `getExternal` method, but I wonder if we can get away with just `origins = '*'`. I don't think there are any security implications of doing that since this is a fully public API anyway. The final option would be to implement a custom cors policy (🤢)

2024-07-26 18:24 UTC, devonbush requested changes
looks great, appreciate all the small fixes.  Requesting changes so that we can figure out what's going on with the CORS stuff

2024-07-26 18:24 UTC, devonbush commented on api-participant/src/main/java/bio/terra/pearl/api/participant/controller/SiteMediaController.java
> +        "https://sandbox.atcp.localhost:3001"
if you were getting CORS errors for this on localhost, it's likely something is off in our vite proxy configs.  Try setting 'changeOrigin' to true for line 34 of `ui-participant/vite.config.ts`

2024-07-26 18:24 UTC, devonbush commented on core/src/main/java/bio/terra/pearl/core/service/survey/AnswerProcessingService.java
> +        if (!ppUser.getProfileId().equals(enrollee.getProfileId())) {
Let's move this logic check to inside the processProxy... function, so that function owns proxy related logic

2024-07-26 18:52 UTC, connorlbark commented on api-participant/src/main/java/bio/terra/pearl/api/participant/controller/SiteMediaController.java
> +        "https://sandbox.atcp.localhost:3001"
Woo! Thanks to Devon, we figured it out. If we just strip the hostname in the survey: `"url": "/api/..."` then it works!

2024-07-26 19:30 UTC, devonbush approved these changes
nice

2024-07-29 18:08 UTC, MatthewBemis approved these changes

2024-07-29 18:33 UTC, merged