[JN-1106] Cancel queued autosaves after form submission
broadinstitute/pearl pull request #1173
Opened 2024-10-30 20:53 UTC by MatthewBemis

#### DESCRIPTION (include screenshots, and mobile screenshots for participant UX)

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

2024-11-01 03:35 UTC, devonbush requested changes
I like the idea, this is complex enough that it definitely needs a test or three

2024-11-12 17:50 UTC, connorlbark approved these changes

2024-11-12 17:50 UTC, connorlbark commented on ui-core/src/autoSaveUtils.test.tsx
> +jest.useFakeTimers()
cool!! i love when there's just. the perfect tool for the job.

2024-11-13 15:20 UTC, devonbush approved these changes

2024-11-13 20:04 UTC, merged