[JN-1231] extract only published
broadinstitute/pearl pull request #1205
Opened 2024-11-13 14:20 UTC by connorlbark

#### DESCRIPTION (include screenshots, and mobile screenshots for participant UX)

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

2024-11-14 01:20 UTC, devonbush requested changes
Functionality looks good--just needs some renaming.  Elsewhere in the codebase we use "active" to delineate surveys/configs that are currently being used in an environment.  "Published" is used to mean something that made it out of sandbox.  So I think the concept you're going for is "extract only active".    Also, see if you can  leverage `findAllByStudyEnvIdWithSurvey` from StudyEnvrionmentSurveyService rather than having to write new DAO methods.

2024-11-14 14:37 UTC, connorlbark commented
> Also, see if you can leverage `findAllByStudyEnvIdWithSurvey` from StudyEnvrionmentSurveyService rather than having to write new DAO methods.

I'm not quite sure how to use this method since survey extraction happens at the portal level, unless we loaded all study environments for a portal, ran `findAllByStudyEnvIdWithSurvey` on each, and then got all the unique results. But I assume that's not what you mean.

2024-11-15 21:36 UTC, devonbush approved these changes

2024-11-18 13:19 UTC, MatthewBemis approved these changes

2024-11-18 14:27 UTC, merged