[JN-565] fix trigger showing editor for inactive triggers
broadinstitute/pearl pull request #1287
Opened 2024-11-27 19:36 UTC by connorlbark

#### DESCRIPTION (include screenshots, and mobile screenshots for participant UX)

If you edit a trigger then hit backspace, it will put the old trigger's UUID in the URL and reload the old, now inactive trigger. You could then save that and cause all kinds of weirdness to happen. This changes the ext service to filter out inactive triggers. If you hit backspace you'll get an error and still see the same trigger - which I think is fine.

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

- Edit a trigger
- Hit the back button
- Observe that it didn't go to the old version of the trigger and instead threw an error

2024-11-28 00:27 UTC, devonbush requested changes
If what we're trying to prevent is editing inactive triggers, let's make that more explicit.  Add a check in the `replace` and `create` methods in this service for if the received object is inactive, and throw an IllegalArgumentException.   And maybe an affordance in the UX for, if a trigger is inactive,  show an alert banner "this trigger is not active"

Otherwise, this will cause unexpected errors when looking at a participant's notification history and clikcing on the trigger.  If the trigger is inactive, we still want to be able to see the config that caused the email

2024-12-06 15:54 UTC, connorlbark commented on ui-admin/src/study/notifications/TriggerList.tsx
> +      <div className="flex-grow-1 bg-white px-3">
drive by alignment fix

2024-12-06 19:04 UTC, devonbush approved these changes
nice! thanks for the revisions

2024-12-09 17:38 UTC, MatthewBemis approved these changes

2024-12-11 17:03 UTC, merged