[JN-260] Align navbar item and button/link config
broadinstitute/pearl pull request #398
Opened 2023-05-24 21:31 UTC by nawatts

Navbar items and buttons/links in landing pages have similar options: internal links, external links, join mailing list buttons. However, their configuration schemas are different.

https://github.com/broadinstitute/pearl/blob/95e5d0f337532b574c9e706ea34853f90129be08/ui-core/src/types/landingPageConfig.ts#L47-L74

https://github.com/broadinstitute/pearl/blob/95e5d0f337532b574c9e706ea34853f90129be08/ui-participant/src/landing/ConfiguredButton.tsx#L7-L34

This makes configuration more difficult since you have to remember which fields to use in which case instead of always using the same fields.

This more closely aligns the two by modifying navbar item and renaming `label` to `text` and combining `anchorLinkPath` and `externalLink` into `href`.

2023-05-24 21:32 UTC, nawatts commented on core/src/main/resources/db/changelog/changesets/2023_05_24_navbar_item.yaml
> +                  name: anchor_link_path
Nothing currently uses these columns, so we can drop and replace them instead of renaming / merging data.

2023-05-25 17:57 UTC, devonbush approved these changes

2023-05-25 18:25 UTC, devonbush requested changes
Please add a test to Navbar.tsx (can be a trivial "does this component render at all" test) to go along with our recent discussion of "let's make all frontend PRs have at least one new test"

2023-05-26 14:11 UTC, nawatts commented on ui-participant/src/Navbar.test.tsx
> +    expect(window.alert).toHaveBeenCalled()
Obviously, this isn't the desired behavior, but leaving it as-is for another ticket/PR.

2023-05-26 16:33 UTC, devonbush approved these changes

2023-05-26 18:14 UTC, MatthewBemis approved these changes

2023-05-30 13:29 UTC, merged