[JN-400] Add createdBy field to TDR dataset
broadinstitute/pearl pull request #406
Opened 2023-05-31 18:25 UTC by MatthewBemis

2023-05-31 18:33 UTC, nawatts approved these changes

2023-05-31 18:33 UTC, nawatts commented on ui-admin/src/study/participants/datarepo/DatasetDashboard.tsx
> +                  <label>Created By:</label> { datasetDetails?.createdBy }
`label` isn't really appropriate here since there's no form element associated with it. I think `dl` would be the better option for this list.

2023-05-31 18:35 UTC, nawatts commented
Re: timezones, we can do what terra-ui does at set `TZ=utc` in the test script.
https://github.com/DataBiosphere/terra-ui/blob/e2c010741f4a13686dcb73f160ba74839488e961/package.json#L74

2023-06-01 16:57 UTC, devonbush requested changes
I'm glad we're adding audit history to these.  For more robustness, let's use AdminUser uuids in the database instead of usernames.  This will make the dashboard a bit less friendly, but I'm fine for now just displaying the uuid.  (we could make a DTO returned by the server for each dataset that includes the username, but I suspect that's more trouble than this is worth for now)

2023-06-01 20:31 UTC, MatthewBemis commented
@devonbush feedback resolved in 15cf3591562e4dcb52b5d779ea01bf0e9330fd9a

2023-06-02 18:36 UTC, devonbush approved these changes

2023-06-02 19:05 UTC, merged