[JN-453] Add new questions to a survey
broadinstitute/pearl pull request #479
Opened 2023-07-14 16:44 UTC by MatthewBemis

This adds the ability to add new questions to a survey page. Not included in this PR is the autofill "scratch box" functionality. That will be coming in the next PR.

![Untitled](https://github.com/broadinstitute/juniper/assets/7257391/b35a1ac0-ac09-4973-8d59-d867d5be9278)

![Screenshot 2023-07-14 at 12 43 38 PM](https://github.com/broadinstitute/juniper/assets/7257391/cf950cdf-8862-4a70-bd53-6eae75f73457)

2023-07-17 18:16 UTC, devonbush approved these changes
Couldn't play around with it because my loaner laptop is refusing to install docker, so I can't get anything to run.  thanks for including the screenshots, though, looks great.  My main thought is that we want to start being robust about how we represent Question type definitions, since that will eventually dictate what users can/can't configure for a question.  Looking through the SurveyJS API, I don't think they have a singular QuestionType definition (they have https://surveyjs.io/form-library/documentation/api-reference/question but that's more of a base class, than a type def), so I think we'll want to roll our own so we're controlling exactly what we do/don't support

2023-07-17 18:16 UTC, devonbush commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +  const baseQuestions: Record<QuestionType, Question> = {
I think this code will get cleaner if we explicitly make an object for the question types:
```
type QuestionTypeDef = {
  name: string
  displayName: string
  hasChoices: boolean
}
const baseQuestionTypeDefs: QuestionTypeDef[] = [{
  name: 'checkbox',
  hasChoices: true,
  displayName: 'Checkbox'
} ...
}]

const baseQuestions = baseQuestionTypeDefs.map(typeDef => ({
   type: typeDef.name,
   name: questionName,
   title: '',
   choices: typeDef.hasChoices ? [] : undefined 
})  

Then you can likewise use a .map call to generate the type options

2023-07-17 18:16 UTC, devonbush commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +import { TextInput } from '../../components/forms/TextInput'
```suggestion
import { TextInput } from 'components/forms/TextInput'
```

2023-07-18 01:39 UTC, devonbush commented
Finally got a chance to check this out - really like how you added all the descriptive helper text -- made it much easier to navigate

2023-07-18 01:40 UTC, devonbush commented
It doesn't have to be in this PR, but we really should enforce non-null name/stableIds -- I accidetnally created one with a blank name, and it was almost impossible to find

2023-07-18 13:12 UTC, breilly2 requested changes
A couple of nice-to-haves, but also an important bug that should be fixed around capturing "Question text" and "Description" after changing question type.

2023-07-18 13:12 UTC, breilly2 commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +              label='Question name'
I think this label should include "stable identifier". I ignored the description (which might actually be a little too low-contrast; I haven't checked it with a11y tooling) and didn't realize that that's what I was choosing.

2023-07-18 13:12 UTC, breilly2 commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +              }}
Some uniqueness validation here would be helpful. I did eventually get an error for a duplicate name, but only when trying to save the survey.

2023-07-18 13:12 UTC, breilly2 commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +            }}>
Switching between `checkbox`, `dropdown`, and `radiogroup` should preserve the configured options, or at least warn that the options will be discarded. I think it's natural to play around with options in a dialog like this to see what's possible and eventually settle back on what was initially chosen, and losing work when doing this is not great. Even better would be to always remember the list of options so that you could switch from, e.g., `dropdown` to `text` and back again without losing work.

I'm also losing "Question text", "Require response", and "Conditionally show this question" when changing the question type, and those should all be valid no matter what type of question it is.

2023-07-18 13:12 UTC, breilly2 commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +            }}>
Bug: I'm also seeing that, even though the "Description" input doesn't get blanked out when changing question type, it doesn't actually get saved.

2023-07-18 13:26 UTC, MatthewBemis commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +              }}
This will be handled as a part of https://broadworkbench.atlassian.net/browse/JN-461

2023-07-18 13:34 UTC, MatthewBemis commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +              label='Question name'
Updated label in f2b09a51

I just checked the contrast for the description text with Axe Devtools and it passed contrast requirements

2023-07-18 13:43 UTC, MatthewBemis commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +            }}>
Agh you're right. Just took a closer look and it seems like there's a bug with descriptions in other parts of the survey editor as well. I'll track it down.

2023-07-18 19:37 UTC, MatthewBemis commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +            }}>
7c9ae04a7377586921c0b138b2d58d47c238c9c5 should fix it

2023-07-19 13:00 UTC, breilly2 commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +              label='Question name'
Cool. Probably just my brain filtering out the description given the relative size and contrast compared to the label.

2023-07-19 13:05 UTC, breilly2 commented on ui-admin/src/forms/designer/NewQuestionForm.tsx
> +            }}>
Cool. That at least makes the behavior predictable, in that I'm not seeing text in the input that doesn't get saved.

2023-07-19 13:06 UTC, breilly2 approved these changes
Thank you for fixing the bug. I do think that the form should be less destructive when changing question type, and should remember as much as possible when toggling between question types (which someone might do while exploring and deciding what they want), but that can be a future enhancement.

2023-07-20 12:36 UTC, MatthewBemis commented
Going to merge this as-is so Erin can play around with it, but will improve the destructive nature of question-switching in a future PR.

2023-07-20 12:37 UTC, merged