JN-573 global participant search bar
broadinstitute/pearl pull request #551
Opened 2023-09-15 14:43 UTC by devonbush

#### DESCRIPTION

Searches substrings of given name, family name, email or shortcode (case-insensitive).  This is a no-frills implementation, so it does not auto-update as the user types, nor does it do name sounds like.  We can add those later if desired. 

 This is implemented as a "Facet" so that it can plug into our existing facet infrastructure that enables url persistence and other goodies.  Now that I'm seeing how the SQLFacet infrastructure is evolving, I think a later PR (when we upgrade to support searching by answer values) will refactor the backend search into a 3-part process so that facets have more comprehensible methods like "getFilteredEnrolleeIds" and "getAssociatedCollections" methods, rather than the current single-query approach which might be more database efficient, but leads to some very opaque implementation methods returning sql-ish stuff.

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*
1. redeploy ApiAdminApp
2. go to https://localhost:3000/ourhealth/studies/ourheart/env/sandbox/participants
3. search for participants by name/shortcode/email
4. reload the page, confirm search and keyword persists

2023-09-15 19:51 UTC, breilly2 requested changes
Looks good. One testing nit: when using the environment drop-down or clicking the "participants" breadcrumb, we should either re-apply the filter or clear the filter text input:

https://github.com/broadinstitute/juniper/assets/19228696/724d29c6-86ec-4fea-b75e-5af86c70505a

2023-09-15 19:51 UTC, breilly2 commented on core/src/main/java/bio/terra/pearl/core/service/participant/search/facets/sql/KeywordFacetSqlGenerator.java
> +                            .formatted(paramName, paramName, paramName, paramName);
I recently learned about referencing formatting arguments positionally which allows you to avoid repeating the value in cases like this:
```suggestion
                    return """
                            (profile.given_name ilike :%1$s 
                              OR profile.family_name ilike :%1$s
                              OR profile.contact_email ilike :%1$s
                              OR enrollee.shortcode ilike :%1$s)
                            """
                            .formatted(paramName);
```

2023-09-18 15:21 UTC, breilly2 approved these changes

2023-09-18 15:28 UTC, MatthewBemis approved these changes
Looks good!

2023-09-18 18:34 UTC, merged