[JN-576] Download participant list
broadinstitute/pearl pull request #585
Opened 2023-10-11 14:36 UTC by MatthewBemis

#### DESCRIPTION

(unit tests coming soon)

This adds the ability to download the participant list as a .csv file. The resulting .csv file will be exactly what is visible in the table when the user clicks the download button; we will respect filters and column selections. I also made a few other related UX tweaks to better match Erin's mockups for the buttons in the upper right corner of the table.

![Screenshot 2023-10-11 at 10 31 09 AM](https://github.com/broadinstitute/juniper/assets/7257391/bf785916-7e4b-4e2f-9611-baab7524cdb7)

![Screenshot 2023-10-11 at 10 31 27 AM](https://github.com/broadinstitute/juniper/assets/7257391/82a25011-cf29-40b2-a2f4-89b95e433dc1)

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

* Launch admin API and UI
* Verify that the download button is disabled if there aren't any rows
* Verify that you can download a csv when there are rows, and that only the visible columns and rows are in the csv
* Verify that there aren't any formatting issues in the file (making sure that everything is escaped when necessary)

2023-10-12 19:23 UTC, MatthewBemis commented on ui-admin/src/study/participants/participantList/ParticipantList.tsx
>          <LoadingSpinner isLoading={isLoading}>
I suggest reviewing this with whitespace changes hidden to get a better idea of what actually changed: https://github.com/broadinstitute/juniper/pull/585/files?w=1

2023-10-12 20:00 UTC, devonbush requested changes
Works well, and love the updated styling.  Some nits and questions below, and two other things:
1. if it's not too hard, we should automatically filter out the "selected" column from the download -- I can't think of any reason why someone would want that, and it would be nice for them not to have to remove it manually
2. Can you go ahead and update MailingListView.tsx to use this new component?

2023-10-12 20:00 UTC, devonbush commented on ui-admin/src/study/participants/participantList/ParticipantList.tsx
> +                <button
Is there a reason you switched from our "Button" default button component to this?  This won't support tooltips when it's disabled, which are nice to give help to users wondering why they can't click somewhere?

2023-10-12 20:00 UTC, devonbush commented on ui-admin/src/util/tableUtils.test.tsx
> +const DEFAULT_INITIAL_DATA = [{ consented: true, name: 'Fred' }, { consented: false, name: 'James' }]
nit: default to me implies it would be empty [].

```suggestion
const SAMPLE_INITIAL_DATA = [{ consented: true, name: 'Fred' }, { consented: false, name: 'James' }]
```

2023-10-12 20:00 UTC, devonbush commented on ui-admin/src/util/tableUtils.tsx
> + */
nice, I like how this is more robust than the basic approach from MailingListView.tsx

2023-10-12 20:00 UTC, devonbush commented on ui-admin/src/util/tableUtils.tsx
> +                downloaded data.
possible wordsmithing for more conciseness? 
```suggestion
                Download <strong>{table.getFilteredRowModel().rows.length}</strong> rows
                to <code>{fileName}.csv</code>. The current data filters and shown columns will be applied.
```

2023-10-12 20:05 UTC, MatthewBemis commented on ui-admin/src/study/participants/participantList/ParticipantList.tsx
> +                <button
Just an oversight. I'll switch that.

2023-10-12 20:14 UTC, MatthewBemis commented on ui-admin/src/util/tableUtils.test.tsx
> +const DEFAULT_INITIAL_DATA = [{ consented: true, name: 'Fred' }, { consented: false, name: 'James' }]
Done in 10e6f428

2023-10-13 16:49 UTC, MatthewBemis commented on ui-admin/src/study/participants/participantList/ParticipantList.tsx
> +                <button
This is done in a693bd01. I also switched `ColumnVisibilityControl` and `DownloadControl` to use `Button`

2023-10-13 18:16 UTC, denniscunningham approved these changes

2023-10-13 18:41 UTC, MatthewBemis commented
@devonbush I've updated the DownloadControl to automatically filter out the `select` column. I took a look at MailingList, and the download flow is a little bit different because it only downloads the selected rows. It wouldn't be a lot of effort to support both cases, but I'd rather check with Erin about how to merge the two different modes in the UI- maybe clicking the `Download` button shows a dropdown or the modal has a radio button that let's the user select between "Download All" and "Download Selected".

Unless you're suggesting that I port the MailingList download to the "Download All" use-case, is it alright if I defer on refactoring that for the moment?

2023-10-13 19:28 UTC, devonbush commented
yup, that makes sense Matt, I forgot the functionality is different.  Thanks for checking it out.

2023-10-13 19:28 UTC, devonbush approved these changes

2023-10-13 19:29 UTC, merged