[JN-595] Improve question validation for height and weight
broadinstitute/pearl pull request #596
Opened 2023-10-18 15:53 UTC by denniscunningham

#### DESCRIPTION
[JN-595](https://broadworkbench.atlassian.net/browse/JN-595)

This PR improves the frontend height and weight validation for survey questions, using the regex validation feature provided by SurveyJS. This allows precise validation criteria and custom validation error messages. See [this](https://docs.google.com/document/d/10iNPRcf2qI0CiuTm8U69W9Agw3AmivQRjpD6j7I-Ql8/edit) document for more information.

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

1. Redeploy ApiAdminApp
2. Re-populate OurHealth (that will update the survey validation). (./scripts/populate_portal.sh ourhealth)
3. Navigate to https://localhost:3000/ourhealth/studies/ourheart/env/sandbox/forms/surveys/oh_oh_basicInfo?readOnly=false and look at the height and weight validation in the JSON Editor view. It should have the same regex as ui-core/src/surveyjs/questionValidation.test.ts.
4. Run ApiParticipantApp
5. Login as “consented@test.com” pwd: “d2p4eva!”
6. Test different height and weight values in the "About You" survey.

[JN-595]: https://broadworkbench.atlassian.net/browse/JN-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-18 23:04 UTC, devonbush requested changes
Looks good, appreciate the attention to detail on the regexes. 

 One extremely important update is needed -- you need to update the `calculatedValues` section at the bottom of the survey so the 'expression' for `oh_oh_basic_weight` is computed from the new kilos field you added instead of the rawWeight field you removed.   To test that the computed value behaves properly, fill out those questions as consented@test.com, and go to `https://localhost:3000/ourhealth/studies/ourheart/env/sandbox/participants/OHSENT/surveys/oh_oh_basicInfo` -- you should see an`oh_oh_basic_weight -- derived` field that contains the participant's weight converted to kilos, regardless of whether it was input as pounds or kilos

2023-10-19 00:53 UTC, denniscunningham commented
@devonbush Thx for the review, and thanks for spotting my mistake. I had persuaded myself that manually testing this from e2e was not necessary. Details matter. :-|

2023-10-19 02:27 UTC, devonbush approved these changes

2023-10-19 12:50 UTC, MatthewBemis approved these changes
Nice! Worked well during testing. I really like the improved validation messages.

2023-10-19 13:18 UTC, merged