Db edit nav logo
broadinstitute/pearl pull request #660
Opened 2023-12-01 23:24 UTC by devonbush

#### DESCRIPTION
This enables editing of the nav logo and the primary brand color from the SiteContentEditor
<img width="1182" alt="image" src="https://github.com/broadinstitute/juniper/assets/2800795/3d876758-8cc3-4fd5-9a03-cce83d703117">
Clicking the "Branding" button pulls up a dialog
<img width="517" alt="image" src="https://github.com/broadinstitute/juniper/assets/2800795/9a6c37f6-bcb0-4a8f-8456-9701e3600e09">

This is bare-bones, mainly intended for internal use when setting up a study just so we don't have to go to the database.  I thought about a color picker for brand color, but I'm not sure it would actually be used -- AFAIK all our past our customers already had a brand color (or Erin chose one), and so exact typing is strongly preferred to picking.  

To make testing easier, I added a link to the participant view from the SiteContentEditor.  If you press it with unsaved changes, an alert pops up letting you know that the preview will not show unsaved changes.

<img width="581" alt="image" src="https://github.com/broadinstitute/juniper/assets/2800795/4cfef1cc-ba7b-44f2-818e-fb61352466a4">

This SiteContent editor is starting to get very noisy, I suspect it doesn't have room for many more controls before it will need some consolidation/rearrangement

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

1. Go to https://localhost:3000/ourhealth/studies/ourheart/env/sandbox/siteContent
2. click the "Branding" button
3. edit the primary brand color, updating it to, say, `#33bb44`
4. click 'ok'
5. save 
6. click the participant view link
7. confirm the new primary brand color is reflected in the UI

2023-12-04 18:13 UTC, denniscunningham requested changes
The create button on the "Create Study" modal is a bit wonky.
It seems like I have to change the portal selection for it to take. (The default choice is not recognized, and reselecting it does not help.)

2023-12-05 15:00 UTC, MatthewBemis approved these changes
Seeing the same Create Study modal behavior as Dennis. Otherwise, the branding stuff itself looks good and worked well.

Agreed that the page is starting to get very crowded, but it's fine for the moment.

2023-12-05 19:20 UTC, devonbush commented
Great catch on the study creation bug -- I wasn't handling initial/current values correctly

2023-12-06 00:20 UTC, denniscunningham approved these changes

2023-12-06 00:44 UTC, merged