JN-770: adding new outreach survey type
broadinstitute/pearl pull request #670
Opened 2023-12-11 21:05 UTC by devonbush

#### DESCRIPTION

This adds the framework (but by no means a complete/refined journey) for a study staff to create messages that appear in the participant dashboard.  This accomplishes that by adding a 'type' field to Surveys, and splitting Surveys into RESEARCH surveys (questionnaires to build a dataset) and OUTREACH (ads).   I'm pleased at how quickly this came together, I think modeling it as a survey type was a big win--it let us implement this quickly while also enhancing general survey capability.

![image](https://github.com/broadinstitute/juniper/assets/2800795/50b7e904-6cc6-4d65-9fa9-208e8cb61662)

We've added a new task status of "VIEWED" to indicate that someone has affirmatively interacted with a task, but not necessarily started it.  

If this survey type pattern proves successful, this could also lay the groundwork for simplifying our code by treating ConsentForms as just a survey type.

This obviously opens up a TON of new functionality and workflows, and many need refinement.  but I don't wan this PR to get too big.  So what I'd propose is that this review focuses mostly on the technical approach, and that we assume at least 4-5 subsequent PRs will be needed before we tell Rachel this is ready to use.
 
 To be done in later PRs:
1. implementing the "blurb" capability (and general participant UX polish).  It's added to the data model in this PR, but to surface it in the dashboard I want to do some refactoring of how task information is cached/fetched.
2. admin UX help for creating the Outreach surveys -- they probably should default to a survey with 1 html question, and could use more info popups and/or Zendesk docs.
3. Ability to only have the outreach survey given to a subset of enrollees
4. Ability to reject/dismiss the outreach survey
5. Ability to track whether the enrollee "said yes" to the outreach survey (obviously, we can't track if they actually joined the external study, but we could track whether they followed a link to it).
6. Ability to assign outreach tasks to existing participants (this is covered in JN-762)

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

1.  restart ApiAdminApp
2. repopulate hearthive `./scripts/populate_portal.sh hearthive`
3. go to https://localhost:3000/hearthive/studies/hh_registry/env/sandbox/forms
4. see the new "Outreach surveys" section
5. go to https://sandbox.hearthive.localhost:3001/
6. sign in as `gelion@test.com`
7. check out the "Foobar study" invitation
8. go to https://localhost:3000/hearthive/studies/hh_registry/env/sandbox/participants/HHGELI/tasks
9. confirm the outreach task now has a status of "VIEWED"

2023-12-12 17:08 UTC, MatthewBemis approved these changes
Overall looks good, just a couple of suggestions.

Also really like your idea of hopefully streamlining consents by using this survey type approach

2023-12-12 17:08 UTC, MatthewBemis commented on ui-participant/src/hub/OutreachTasks.tsx
> +        return <div className="col-md-4 col-sm-12">
This div needs a unique `key` prop

2023-12-12 17:08 UTC, MatthewBemis commented on core/src/main/java/bio/terra/pearl/core/service/survey/SurveyResponseService.java
> +            } else if (task.getStatus() == TaskStatus.NEW && response.getAnswers().size() == 0) {
Should this check for `TaskStatus.NEW || TaskStatus.VIEWED` instead of just `NEW`? As it is right now, this sets outreach surveys to `IN_PROGRESS` if they've been viewed more than once.

2023-12-12 17:08 UTC, MatthewBemis commented on ui-admin/src/study/StudyContent.tsx
> +          <li className="mb-3 rounded-2 p-3" style={{ background: '#efefef' }}>
Nice style changes on this page!

2023-12-12 17:36 UTC, devonbush commented on core/src/main/java/bio/terra/pearl/core/service/survey/SurveyResponseService.java
> +            } else if (task.getStatus() == TaskStatus.NEW && response.getAnswers().size() == 0) {
nice catch, thanks

2023-12-18 19:13 UTC, denniscunningham requested changes
Just marking as 'Request changes' to get your guidance on StudyResearchTasks. 
Otherwise looks good.

2023-12-18 19:13 UTC, denniscunningham commented on core/src/main/java/bio/terra/pearl/core/service/participant/WithdrawnEnrolleeService.java
> +    } catch (JsonProcessingException e) {
Nice.

2023-12-18 19:13 UTC, denniscunningham commented on core/src/main/java/bio/terra/pearl/core/service/study/StudyService.java
> +                System.out.println("deleting orphaned study " + studyId);
Are these `println` statements permanent? Do they want to be log statements?

2023-12-18 19:13 UTC, denniscunningham commented on core/src/main/resources/db/changelog/changesets/2023_12_08_survey_type.yaml
> +                  name: blurb
In the future, might this be used for anything other than outreach?
Just curious about naming.

2023-12-18 19:13 UTC, denniscunningham commented on core/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - include:
Just curious why this is not in the last position in the file.

2023-12-18 19:13 UTC, denniscunningham commented on populate/src/test/java/bio/terra/pearl/populate/PopulateHeartHiveTest.java
> +        txTemplate.execute(status -> {
Just curious... why the change? Does `TransactionTemplate` provide something that `@Transactional` does not?
Since `TransactionTemplate` is new to me, what transaction manager is it using? Is there a default?

2023-12-18 19:13 UTC, denniscunningham commented on ui-admin/src/study/participants/enrolleeView/EnrolleeView.tsx
> +                <CollapsableMenu header={'Outreach'} headerClass="text-black" content={
This will always appear, even for studies without an outreach concept (like OurHealth). Is that what we want? Is this a feature we expect all studies may want to use?

2023-12-18 19:13 UTC, denniscunningham commented on ui-participant/src/hub/HubPage.tsx
> +        <div className="hub-dashboard mx-auto"
Feels like this could get lost (due to placement) for a study with a handful of surveys like OurHealth.
But we are rethinking the dashboard.
Ideally, where would this be?

2023-12-18 19:13 UTC, denniscunningham commented on ui-participant/src/hub/StudyResearchTasks.tsx
> +export default function StudyResearchTasks(props: StudyResearchTasksProps) {
Is it safe to assume this is a cut and paste from HubPage, or should we do a detailed review as if new code?

2023-12-18 19:13 UTC, denniscunningham commented on ui-admin/src/study/StudyContent.tsx
> +            <h6>Outreach</h6>
As in the ptp detail page, `Outreach` is always listed, even if the study does not have an outreach concept.

2023-12-18 19:45 UTC, devonbush commented on core/src/main/java/bio/terra/pearl/core/service/study/StudyService.java
> +                System.out.println("deleting orphaned study " + studyId);
debug leftovers, thanks -- will convert to logs

2023-12-18 19:46 UTC, devonbush commented on core/src/main/resources/db/changelog/changesets/2023_12_08_survey_type.yaml
> +                  name: blurb
Quite likely.  "Outreach" was the most generic name I could think of besides "non-research".  And I'm not sure whether other uses would require creation of a third type

2023-12-18 20:25 UTC, devonbush commented on populate/src/test/java/bio/terra/pearl/populate/PopulateHeartHiveTest.java
> +        txTemplate.execute(status -> {
will add a comment explaining -- basically we have to do this transaction manually so that we can set a savepoint inside it

2023-12-18 20:25 UTC, devonbush commented on ui-admin/src/study/StudyContent.tsx
> +            <h6>Outreach</h6>
yeah, I'm torn on "hide things that aren't relevant" vs. "keep features visible so admins know where to look".  I'm inclined to keep everything visible for now, and then we can reduce clutter latter

2023-12-18 20:25 UTC, devonbush commented on ui-admin/src/study/participants/enrolleeView/EnrolleeView.tsx
> +                <CollapsableMenu header={'Outreach'} headerClass="text-black" content={
for now, yes, i think it will be good to advertise this feature.  Later, we may want to only show if relevant

2023-12-18 20:25 UTC, devonbush commented on ui-participant/src/hub/HubPage.tsx
> +        <div className="hub-dashboard mx-auto"
great question!

2023-12-18 20:25 UTC, devonbush commented on ui-participant/src/hub/StudyResearchTasks.tsx
> +export default function StudyResearchTasks(props: StudyResearchTasksProps) {
yes, this is cut-paste, thanks

2023-12-18 20:25 UTC, devonbush commented on core/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - include:
the mysteries of git merge -- I'll reorder to make sense

2023-12-19 00:11 UTC, denniscunningham approved these changes

2023-12-19 00:11 UTC, denniscunningham commented on core/src/main/resources/db/changelog/changesets/2023_12_08_survey_type.yaml
> +                  name: blurb
Sorry, I was not clear... I was referring to 'blurb' so should have called that out.
I was thinking about what else that field might be used for, and whether a different name might have more legs.
No biggie. The name just seemed specific to one case.

2023-12-19 00:11 UTC, denniscunningham commented on populate/src/test/java/bio/terra/pearl/populate/PopulateHeartHiveTest.java
> +        txTemplate.execute(status -> {
Ty!
I'll follow-up with you on what transaction manager is used here.

2023-12-19 15:36 UTC, devonbush commented
Ah, yeah, I could easily see this changing to "description" + "short_description" + "html_preview" etc...  Definitely not committed to 'blurb'

2023-12-19 15:37 UTC, merged