[JN-789] Cohort builder modal
broadinstitute/pearl pull request #690
Opened 2024-01-08 14:52 UTC by MatthewBemis

#### DESCRIPTION

Wanted to just get this out into review because I've been sitting on it for a bit. This will need integration work with the backend once the rules engine and everything is in place, so for now it's just visible to superusers.

During demo, it was mentioned that it would be nice to make the field selector searchable, allowing the user to easily find a field if there are hundreds to sift through. I attempted to override the `fieldSelector` component of react-querybuilder , but React-Select didn't play too nicely with the internal rules builder. I'm sure we can get it to work, but it was starting to be a bit of a time sink and I didn't want to invest too much time before knowing if this was definitely the path we wanted to go down. For now, I think it's okay if HeartHive has to sift through a few fields- they have fewer surveys and fields than OurHealth.

<img width="1152" alt="Screenshot 2024-01-08 at 9 50 42 AM" src="https://github.com/broadinstitute/juniper/assets/7257391/20e5114d-09d7-4327-8927-592307e72256">

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

1) Go to the portal list: https://localhost:3000/
2) Select a portal and study and try adding some criteria (note this uses live to gather the fields, so if the live environment for your selected study isn't initialized then it will be lacking options)
3) You can't save it yet, so you'll see a "Not yet implemented" message when you click Create

2024-01-08 20:29 UTC, devonbush requested changes
Good stuff!  A few suggestions, the blocking one is moving the package.json dependency, the others are optional

2024-01-08 20:29 UTC, devonbush commented on package.json
> +  "dependencies": {
This should be specified in the ui-admin/package.json instead

2024-01-08 20:29 UTC, devonbush commented on ui-admin/src/study/CreateNewCohortModal.tsx
> +        <Select isDisabled={!selectedPortal} inputId={selectStudyInputId} options={studyOptions}
I like that you put the study selector here so this component can get reused in other places.

2024-01-08 20:29 UTC, devonbush commented on ui-admin/src/study/CreateNewCohortModal.tsx
> +  const [selectedStudy, setSelectedStudy] = useState<PortalStudy>()
selectedStudy and selectedPortal should each default if there's only one study/portal available for that user

2024-01-08 20:29 UTC, devonbush commented on ui-admin/src/study/CreateNewCohortModal.tsx
> +  }, [selectedStudy])
You can just add a 3rd argument to useLoadingEffect to customize the error message, you don't have to check for the error yourself
```suggestion
      setParticipantFields(result)
  }, [selectedStudy], 'failed to load cohort criteria options')
```

2024-01-15 14:14 UTC, devonbush approved these changes

2024-01-17 17:18 UTC, connorlbark approved these changes
Works well for me! I'm wondering if we should (in the future) override the styling to make it fit more in-line with the theming of our application, but that's definitely out of the scope of this.

2024-01-24 17:16 UTC, merged