[JN-970] add b2c error page and logging
broadinstitute/pearl pull request #820
Opened 2024-03-27 16:33 UTC by connorlbark

#### DESCRIPTION

Adds an error page when b2c returns an error.

Desktop
<img width="1512" alt="image" src="https://github.com/broadinstitute/juniper/assets/17440010/af09930d-b24d-41eb-b62e-31844f3846cb">

Mobile
<img width="376" alt="image" src="https://github.com/broadinstitute/juniper/assets/17440010/acbca94d-f26c-453b-8557-a62b9abd4352">

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

You have to trick the redirect system to believe there was an error. You can do that by adding:

```
      auth.error = { message: 'test message', stack: 'test stack', name: 'test error' }
```

at `RedirectFromOauth.tsx:39`

Then, just try logging in or registering like normal and observe that the backend logs at an error level and you get an error page.

2024-03-28 01:59 UTC, devonbush requested changes
this is great, just needs some text cleanup

2024-03-28 01:59 UTC, devonbush commented on ui-participant/src/login/AuthError.tsx
> +            <span>Oops!</span>
"oops" probably isn't tone-appropriate for a rare-disease site.  I'd omit this word

2024-03-28 01:59 UTC, devonbush commented on ui-participant/src/login/AuthError.tsx
> +            Something went wrong with our authentication service. Please try again later.
```suggestion
            Something went wrong with our authentication service. Please try again.  If the problem persists, please contact ${supportEmailAddress}
```
you can get the portal-specific support email address from `usePortalEnv().portalEnv.portalEnvrionmentConfig.sourceEmailAddress`

2024-03-28 19:18 UTC, MatthewBemis approved these changes

2024-04-01 19:48 UTC, devonbush approved these changes

2024-04-01 20:26 UTC, merged