[JN-971] WIP Search exp query builder
broadinstitute/pearl pull request #830
Opened 2024-04-02 17:04 UTC by connorlbark

#### DESCRIPTION

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

2024-04-04 17:33 UTC, devonbush requested changes
Overall looks good.  My main feedback is to put the new search methods side-by-side with the old, rather than building a parallel class hierarchy.  That will make it easier to compare/contrast functionality, and to clean out old code once it's no longer needed

2024-04-04 17:33 UTC, devonbush commented on api-admin/src/main/java/bio/terra/pearl/api/admin/controller/search/EnrolleeSearchExpressionController.java
> +  @Override
how about we just make this "getExpressionSearchFacets" and put this in EnrolleeSearchController.  That will make it easier to see/compare it side-by-side with the existing getSearchFacets() path, so we don't forget about either path

2024-04-04 17:33 UTC, devonbush commented on api-admin/src/main/java/bio/terra/pearl/api/admin/controller/search/EnrolleeSearchExpressionController.java
> +    authUtilService.authUserToStudy(user, portalShortcode, studyShortcode);
how about we make a new EnrolleeSearchExtService to handle the auth.  The auth rules for search are going to get complicated (e.g. some users will be able to see PHI, some wont).  Then you can also relocate the existing EnrolleeExtService.search method there

2024-04-04 17:33 UTC, devonbush commented on core/src/main/java/bio/terra/pearl/core/service/search/EnrolleeSearchExpressionService.java
> +public class EnrolleeSearchExpressionService {
let's move these methods inside EnrolleeSearchService

2024-04-04 17:33 UTC, devonbush commented on ui-admin/src/api/api.tsx
> +  async getSearchFacetsV2(portalShortcode: string, studyShortcode: string, envName: string):
```suggestion
  async getExpressionSearchFacets(portalShortcode: string, studyShortcode: string, envName: string):
```

2024-04-04 17:46 UTC, connorlbark commented on api-admin/src/main/java/bio/terra/pearl/api/admin/controller/search/EnrolleeSearchExpressionController.java
> +  @Override
I was doing it this way to make it easier to delete the code in one big fell swoop later / make it more clear what code is deprecated versus new, but I could go either way. Happy to move that over

2024-04-05 15:48 UTC, MatthewBemis reviewed
Just a few nits/testing notes

2024-04-05 15:48 UTC, MatthewBemis commented on ui-admin/src/util/formatQueryBuilderAsSearchExp.tsx
> +  console.log('called')
```suggestion
```

2024-04-05 15:48 UTC, MatthewBemis commented on core/src/main/java/bio/terra/pearl/core/service/participant/search/EnrolleeSearchService.java
> +        fields.put("age", SearchValue.SearchValueType.INTEGER);
While testing locally, I'm getting an NPE when trying to save a survey with an expression that uses the `age` facet:

```
java.lang.NullPointerException: temporal
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at java.base/java.time.LocalDate.from(LocalDate.java:394)
	at java.base/java.time.LocalDate.until(LocalDate.java:1702)
	at java.base/java.time.Period.between(Period.java:389)
	at bio.terra.pearl.core.service.search.terms.AgeTerm.extract(AgeTerm.java:28)
	at bio.terra.pearl.core.service.search.expressions.EnrolleeTermComparisonFacet.evaluate(EnrolleeTermComparisonFacet.java:40)
	...
```

2024-04-05 15:48 UTC, MatthewBemis commented on ui-admin/src/search/SearchQueryBuilder.tsx
> +      }}
Nice, thanks for restyling everything! The original PoC was certainly ugly

2024-04-05 15:48 UTC, MatthewBemis commented on ui-admin/src/search/SearchQueryBuilder.tsx
> +      key={'test2'} id={'test2'}
Are these "test" keys/ids leftovers from iterating during development?

2024-04-05 15:58 UTC, connorlbark commented on ui-admin/src/search/SearchQueryBuilder.tsx
> +      key={'test2'} id={'test2'}
Oh man I accidentally left a lot in that was my bad, thanks for catching all that.

2024-04-05 17:40 UTC, MatthewBemis approved these changes

2024-04-10 13:14 UTC, devonbush approved these changes

2024-04-10 14:09 UTC, merged