JN-975
broadinstitute/pearl pull request #840
Opened 2024-04-08 19:12 UTC by ssettipalli

#### DESCRIPTION
group portal studies by portal name

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

populate test studies
start admin portal
Navigate to juniper admin portal.
verify that studies are grouped and each group has a heading with portal name

2024-04-08 19:13 UTC, ssettipalli commented on populate/src/main/java/bio/terra/pearl/populate/service/BaseSeedPopulator.java
> +                    "adminUsers/andrew.json", "adminUsers/pegah.json", "adminUsers/sampath.json");
not really relate to PR . just a setup

2024-04-08 19:13 UTC, ssettipalli commented on populate/src/main/resources/seed/adminUsers/sampath.json
> +{
not really relate to PR . just a setup
could have been in a diff PR

2024-04-09 12:49 UTC, MatthewBemis approved these changes
Looks good! Can you also include a screenshot of this change in the PR description? We usually include these for frontend changes to make it easier to review and confirm expected UX

2024-04-09 13:11 UTC, ssettipalli commented
<img width="1594" alt="Screenshot 2024-04-09 at 8 09 48 AM" src="https://github.com/broadinstitute/juniper/assets/26553609/940f8ee4-517b-48ac-86cf-3bec5ed9929b">

2024-04-10 13:07 UTC, devonbush requested changes
Looks good, thanks!  One accessibility cleanup and this will be good to go.  Also, for future branches, please include a couple words of description in the branch name.  e.g. `JN-975-portal-list-names`.  This helps reviewers pulling your branch not get confused as they are switching branches locally

2024-04-10 13:07 UTC, devonbush commented on ui-admin/src/HomePage.tsx
> +        { portalList.sort((a, b) => a.name.localeCompare(b.name)).flatMap(portal => [
I think this would be semantically clearer and more accessible via screenreader if you treated this as a list-of-lists, rather than putting titles in interstitial area
```suggestion
        { portalList.sort((a, b) => a.name.localeCompare(b.name)).flatMap(portal => 
          <li key = "portal.shortcode">
          <span className={'mt-2'}>{portal.name}</span>
            <ul className="list-group list-group-flush">
              ...portal.portalStudies.sort((a, b) =>
```

2024-04-10 15:39 UTC, devonbush approved these changes

2024-04-10 15:39 UTC, devonbush commented on ui-admin/src/HomePage.tsx
> +          <li key = "portal.shortcode">
```suggestion
          <li key = {portal.shortcode}>
```

2024-04-10 15:39 UTC, devonbush commented on ui-admin/src/HomePage.tsx
> +          <li key = "portal.shortcode">
I think this was a typo in my suggestion

2024-04-11 01:37 UTC, devonbush approved these changes

2024-04-11 11:36 UTC, merged