[JN-1112] create core family linkage models
broadinstitute/pearl pull request #925
Opened 2024-06-05 18:26 UTC by connorlbark

#### DESCRIPTION (include screenshots, and mobile screenshots for participant UX)

#### TO TEST:  *(simple manual steps for confirming core behavior -- used for pre-release checks)*

2024-06-05 18:27 UTC, connorlbark commented on core/src/main/java/bio/terra/pearl/core/model/participant/RelationshipType.java
> +    PROXY, FAMILY;
There are many places (mostly in the UI) that treat _any_ enrollee relation as providing full access; that is the subject of a future PR.

2024-06-05 18:35 UTC, connorlbark commented on core/src/test/java/bio/terra/pearl/core/service/survey/SurveyTaskDispatcherTest.java
> +        assertThat(tasks.stream().map(ParticipantTask::getTargetStableId).toList(), containsInAnyOrder("medForm", "followUp"));
drive by flaky test fix

2024-06-05 22:39 UTC, devonbush requested changes
Overall, agree with the approach.  The blocker is that this needs to be audited.  And we should do some thinking about the best way to handle the shortcodes

2024-06-05 22:39 UTC, devonbush commented on core/src/main/java/bio/terra/pearl/core/service/participant/FamilyService.java
> +public class FamilyService extends CrudService<Family, FamilyDao> {
This should extend DataAuditedService so we can track creation/deletion of families

2024-06-05 22:39 UTC, devonbush commented on core/src/main/java/bio/terra/pearl/core/service/participant/FamilyService.java
> +     */
let's pull this into a utlity method, and also let's make sure that Enrollee and Family shortcodes have the same length and allowed chars.   I think the right approach is to have a ShortcodeUtils  class with the LENGTH and ALLOWED_CHARS utility method that takes as an argument a `shortcodeAlreadyExists` String -> boolean function.   

Should we prefix Family shortcodes with `F_` or some similar prefix so they're distinguishable at a glance from Enrollee shortcodes?

2024-06-10 14:39 UTC, devonbush approved these changes
nice, and thanks for remembering to update the enrollee withdraw logic!

2024-06-10 14:39 UTC, devonbush commented on core/src/main/java/bio/terra/pearl/core/service/participant/ShortcodeUtilService.java
> +public class ShortcodeUtilService {
Generally, something is either a utility or a service.  I think of utilities as non-Spring components that encapsulate pure business logic.  So I'd rename this to ShortcodeService to connote that this hits the database  and has some spring stuff injected into it

2024-06-10 14:39 UTC, devonbush commented on ui-participant/src/test-utils/test-proxy-environment.tsx
> +} from '../api/api'
```suggestion
} from 'api/api'
```

2024-06-10 17:05 UTC, MatthewBemis approved these changes
:shipit:

2024-06-10 17:08 UTC, merged